### ISSUE TITLE
Can you share how the .mat file is created?

### ISSUE THREAD

**Issue by louzhao8712** [geekfeiw/WiSPPN#1]
Hi @geekfeiw 
This is a great project. Can you share how the examples/oct17set1_fw_1814.mat file was created?

I looked into your wifiperson project and only see code to generate .avi, csi raw data and timestamp.

Thanks

**Comment by geekfeiw** [comment]
This mat file include csi_serial, frame, jointsVector, and jointsMatrix.
The csi_serial and frame are synchronized by the timestamps of the csi data and avi data. 

I suppose what you want to know is how to generate jointsVector and jointsMatrix: 
[AlphaPose](https://github.com/MVIG-SJTU/AlphaPose) takes one video file as input, e.g., one video with a total of 100 frames, and generates 100 json files. Each json files corresponds with one frame, and contains information of person body joint coordinates and confidences.

The jointVectors is created with matlab codes as  

`
fid  = fopen('frameName.json');
raw = fred(fid, inf);
str = char(raw');
val = jsondecode(str);
joints = val.bodies(1).joints;

x_axis = joints(1:3:end);
y_axis = joints(2:3:end);
confidences = joints(3:3:end);

jointsVector = [x;y;c;c];
`

The jointsMatrix is generated from jointsVector as descripted as in the [tech report](https://arxiv.org/pdf/1904.00277.pdf) figure 4.

**Comment by geekfeiw** [comment]
> Hi @geekfeiw
> This is a great project. Can you share how the examples/oct17set1_fw_1814.mat file was created?
> 
> I looked into your wifiperson project and only see code to generate .avi, csi raw data and timestamp.
> 
> Thanks

This mat file include csi_serial, frame, jointsVector, and jointsMatrix.
The csi_serial and frame are synchronized by the timestamps of the csi data and avi data. 

I suppose what you want to know is how to generate jointsVector and jointsMatrix: 
[AlphaPose](https://github.com/MVIG-SJTU/AlphaPose) takes one video file as input, e.g., one video with a total of 100 frames, and generates 100 json files. Each json files corresponds with one frame, and contains information of person body joint coordinates and confidences.

The jointVectors is created with matlab codes as  

`
fid  = fopen('frameName.json');
raw = fred(fid, inf);
str = char(raw');
val = jsondecode(str);
joints = val.bodies(1).joints;

x_axis = joints(1:3:end);
y_axis = joints(2:3:end);
confidences = joints(3:3:end);

jointsVector = [x;y;c;c];
`

The jointsMatrix is generated from jointsVector as descripted in the [tech report](https://arxiv.org/pdf/1904.00277.pdf) figure 4.

**Comment by louzhao8712** [comment]
The jointsVector and jointsMatrix info is very useful. 
"The csi_serial and frame are synchronized by the timestamps of the csi data and avi data." Can you share  the code how did you sync the timestamp?

Thanks

**Comment by geekfeiw** [comment]
With released tools in wifiperson project, we have Unix time of csi and avi.

(1) Then we just watch the video, and mark the start frame and end frame of someone appearing in the camera. Taking the following as an example.

videoName | cameraStrat | cameraEnd | info | WiFiStart | WiFiEnd
-- | -- | -- | -- | -- | --
oct17set1 | 1409 | 2432 | fw | 6328 | 11375
oct17set1 | 2759 | 3498 | sp | 12995 | 16672
oct17set1 | 3670 | 4740 | hzy | 17502 | 22815
oct17set1 | 4943 | 6280 | dh | 23817 | 30463
oct17set1 | 6570 | 7440 | stan | 31893 | 36218

Someone, e.g., fw, appears at the No.1409 frame, and leaves at the time of No.2432 frame. 

(2) We mark the camera timestamp,  and find the time of no.1409 in camera timestamp is closest to the the no.6328 in csi timestamp. The same operation on the no.2432.

(3) Then, we have frames from no.1409 to no.2432,  and have csi_serial from no.6328 to no.11375.

(4) Finally, we align one frame with 5 csi for camera is 20Hz and wifi csi is 100Hz.

We call above operation the synchronization.

**Comment by louzhao8712** [comment]
Thanks for the detailed answer

**Comment by louzhao8712** [comment]
Hi @geekfeiw 

About the csi absolute value in the oct17set1_fw_1814.mat file, did you compute it using  Intel's internal reference level or you have scaled the csi with RSSI and AGC first? i.e used matlab function` csi = get_scaled_csi(csi_entry);`  provided by the csitool

Finally is the csi unit in linear or db?

**Comment by geekfeiw** [comment]
I just used **read_bf_file**, I am not familiar with the difference. Could you explain it?

And the csi unit is in linear.

**Comment by louzhao8712** [comment]
https://github.com/dhalperi/linux-80211n-csitool-supplementary/blob/master/matlab/get_scaled_csi.m

This function scaled the original csi to SNR unit. It combine the RSSI and AGC values together to get RSS in dBm, and include noise to get SNR



scale = rssi_pwr / (csi_pwr / 30);
total_noise_pwr = thermal_noise_pwr + quant_error_pwr;

ret = csi * sqrt(scale / total_noise_pwr);
