### ISSUE TITLE
The Pose Adjacent Matrix is different from paper.

### ISSUE THREAD

**Issue by BlueAnthony** [geekfeiw/WiSPPN#2]
Pose Adjacent Matrix in paper is 3x18x18.
But, Pose Adjacent Matrix in prepare_data.m & train.py is 4x18x18.

**Comment by geekfeiw** [comment]
@BlueAnthony   Aha, we compute loss via _c||x-x'||+c||y-y'||_, where c are used twice. The 4th dimension of Pose Adjacent Matrix is a duplicate of its 3rd dimension. We did this for a more efficient code writing.
